#' Perform predictive modeling using images or videos
#'
#' @param obsY A numeric vector containing observed outcomes to predict.
#' @param imageKeysOfUnits A vector of length `length(obsY)` specifying the unique image ID associated with each unit. Samples of `imageKeysOfUnits` are fed into the package to call images into memory.
#' @param file Path to a tfrecord file generated by `WriteTfRecord`.
#' @param conda_env A `conda` environment where computational environment lives, usually created via `causalimages::BuildBackend()`. Default = `"CausalImagesEnv"`.
#' @param conda_env_required A Boolean stating whether use of the specified conda environment is required.
#' @param X An optional numeric matrix containing tabular information. `X` is normalized internally.
#' @param figuresTag A string specifying an identifier that is appended to all figure names.
#' @param figuresPath A string specifying file path for saved figures made in the analysis.
#' @param plotBands Reserved for compatibility with older predictive plotting code.
#'   `PredictiveRun()` currently does not use this argument.
#' @param nSGD Number of stochastic gradient descent (SGD) iterations. Default = `400L`
#' @param nBoot Reserved for compatibility. `PredictiveRun()` currently does not
#'   bootstrap predictive uncertainty.
#' @param batchSize Batch size used in SGD optimization. Default = `50L`.
#' @param useTrainingPerturbations Boolean specifying whether to randomly perturb the image axes during training to reduce overfitting.
#' @param optimizeImageRep Boolean specifying whether to optimize over the image model representation (or only over downstream parameters).
#' @param dropoutRate Dropout rate used in training to prevent overfitting (`dropoutRate = 0` corresponds to no dropout).
#' @param droppathRate Droppath rate used in training to prevent overfitting (`droppathRate = 0` corresponds to no droppath).
#' @param testFrac Default = `0.1`. Fraction of observations held out as a test set to evaluate out-of-sample loss values.
#' @param strides (default = `2L`) Integer specifying the strides used in the convolutional layers.
#' @param plotResults Reserved for compatibility with older predictive plotting
#'   code. `PredictiveRun()` currently does not plot results.
#' @param dataType (default = `"image"`) String specifying whether to assume `"image"` or `"video"` data types.
#' @param temporalAggregation String specifying how to aggregate embeddings across time periods for video/image sequence data. Options are `"transformer"` (default) which uses a temporal transformer with attention pooling, or `"concatenate"` which simply concatenates the frame-level embeddings.
#' @param nWidth_ImageRep Integer specifying width of image model representation.
#' @param nDepth_ImageRep Integer specifying depth of image model representation.
#' @param nWidth_Dense Integer specifying width of image model representation.
#' @param nDepth_Dense Integer specifying depth of dense model representation.
#' @param kernelSize Dimensions used in spatial convolutions.
#' @param TfRecords_BufferScaler The buffer size used in `tfrecords` mode is `batchSize*TfRecords_BufferScaler`. Lower `TfRecords_BufferScaler` towards 1 if out-of-memory problems.
#' @param modelPath Path to save the trained model artifact. A metadata sidecar is
#'   also written to `paste0(modelPath, ".meta.rds")`. Default = `"./trained_model.eqx"`.
#' @param metricsPath Path to save the evaluation metrics as a RDS file. Default = `"./evaluation_metrics.rds"`.
#' @param fileTransport Path to a tfrecord file for out-of-sample scoring with the
#'   trained predictive artifact.
#' @param imageKeysOfUnitsTransport A vector of image keys for the requested
#'   transport observations.
#' @param XTransport Optional numeric matrix of transport covariates. Required when
#'   `X` is supplied during model training and `fileTransport` is used.
#' @param inputAvePoolingSize Integer specifying average pooling size for downshifting image resolution. Default = `1L` (no downshift).
#' @param useScalePerturbations Boolean specifying whether to use scale perturbations during training. Default = `FALSE`.
#' @param Sys.setenv_text Optional string for setting environment variables before Python initialization.
#' @param XCrossModal Boolean specifying whether to use cross-modal learning with tabular data. Default = `TRUE`.
#' @param XForceModal Boolean specifying whether to force modal learning. Default = `FALSE`.
#' @param imageModelClass String specifying the image model architecture. Options include `"VisionTransformer"` (default) or `"CNN"`.
#' @param pretrainedModel Optional string specifying a pretrained model to use. Options include `"vit-base"`, `"clip-rsicd"`, or HuggingFace model names with `"transformers-"` prefix.
#' @param nonLinearScaler Optional string specifying non-linear scaling function for outputs.
#' @param nDepth_TemporalRep Integer specifying depth of temporal representation model. Default = `3L`.
#' @param patchEmbedDim Integer specifying patch embedding dimension for Vision Transformer. Default = `16L`.
#' @param learningRateMax Maximum learning rate for the optimizer. Default = `0.001`.
#' @param TFRecordControl Optional list for advanced TFRecord configuration.
#' @param image_dtype String specifying image data type. Options are `"float16"` (default), `"bfloat16"`, or `"float32"`.
#' @param atError String specifying behavior on error. Options are `"stop"` (default) or `"debug"`.
#' @param seed Optional integer for reproducibility.
#'
#' @return Returns a list consisting of
#' \itemize{
#'   \item `predictedY` Predicted values for all units.
#'   \item `predictedY_transport` Predicted values for the requested transport
#'   units, or `NULL` when `fileTransport` is not supplied.
#'   \item `ModelEvaluationMetrics` Rigorous evaluation metrics (e.g., MSE, R2 for continuous; AUC, accuracy for binary).
#' }
#'
#' @section References:
#' \itemize{
#' \item  Connor T. Jerzak, Fredrik Johansson, Adel Daoud. Integrating Earth Observation Data into Causal Inference: Challenges and Opportunities. *ArXiv Preprint*, 2023.
#' }
#'
#' @examples
#' # For a tutorial, see
#' # github.com/cjerzak/causalimages-software/
#'
#' @export
#' @md

PredictiveRun <- function(
    obsY,
    imageKeysOfUnits = NULL,
    file = NULL,
    fileTransport = NULL,
    imageKeysOfUnitsTransport = NULL,
    XTransport = NULL,
    nBoot = 10L,
    inputAvePoolingSize = 1L,
    useTrainingPerturbations = T,
    useScalePerturbations = F,
    X = NULL,
    conda_env = "CausalImagesEnv",
    conda_env_required = T,
    Sys.setenv_text = NULL,
    
    figuresTag = NULL,
    figuresPath = "./",
    plotBands = 1L,
    plotResults = T,
    
    XCrossModal = T,
    XForceModal = F, 
    optimizeImageRep = T,
    nWidth_ImageRep = 64L,  nDepth_ImageRep = 1L, kernelSize = 5L,
    nWidth_Dense = 64L,  nDepth_Dense = 1L,
    imageModelClass = "VisionTransformer",
    pretrainedModel = NULL, 
    
    strides = 2L,
    nonLinearScaler = NULL,
    nDepth_TemporalRep = 3L,
    patchEmbedDim = 16L,
    dropoutRate = 0.1,
    droppathRate = 0.1, 
    batchSize = 16L,
    nSGD  = 400L,
    testFrac = 0.05,
    TfRecords_BufferScaler = 4L,
    learningRateMax = 0.001,
    TFRecordControl = NULL,
    dataType = "image",
    temporalAggregation = "transformer",
    image_dtype = "float16",
    atError = "stop",
    seed = NULL,
    modelPath = "./trained_model.eqx",
    metricsPath = "./evaluation_metrics.rds"
){
  {
    # IMPORTANT: If using a pretrained model that requires torch/transformers,
    # initialize torch BEFORE JAX/TF/NumPy to avoid import conflicts
    if (pretrained_model_requires_torch(pretrainedModel)) {
      if (!"torch" %in% ls(envir = cienv)) {
        initialize_torch(conda_env = conda_env,
                         conda_env_required = conda_env_required,
                         Sys.setenv_text = Sys.setenv_text)
      }
    }

    if(!ci_backend_ready()) {
      initialize_jax(conda_env = conda_env,
                     conda_env_required = conda_env_required,
                     Sys.setenv_text = Sys.setenv_text)
    }
    message2(sprintf("Default device: %s",cienv$jnp$array(0.)$devices()))

    # set float type
    image_dtype_char <- as.character(image_dtype)
    dtype_info <- ci_predictive_dtype_info(image_dtype_char)
    image_dtype_tf <- dtype_info$image_dtype_tf
    ComputeDtype <- image_dtype <- dtype_info$ComputeDtype
    if(is.null(seed)){ seed <- as.integer(stats::runif(1,1,10000)) }
    seed <- ci_int32_scalar(seed, "PredictiveRun seed")
    obsY <- f2n(obsY)
    
    # set memory growth for tensorflow 
    for(device_ in cienv$tf$config$list_physical_devices()){
      try(cienv$tf$config$experimental$set_memory_growth(device_, T),T)
    }
  }
  
  message2("Setting input types in PredictiveRun()...") 
  if(!is.null(pretrainedModel)){ pretrainedModel <- as.character(pretrainedModel) } 
  if(!is.null(optimizeImageRep)){ optimizeImageRep <- as.logical(as.character(optimizeImageRep)) }
  if(!is.null(imageModelClass)){ imageModelClass <- as.character(imageModelClass) }
  if(!is.null(nWidth_ImageRep)){ nWidth_ImageRep <- as.integer(f2n(nWidth_ImageRep)) }
  predictive_seed_value <- function(offset = 0L, label = "PredictiveRun seed") {
    ci_seed_int32(seed = seed, offset = offset, label = label)
  }
  predictive_seed_key <- function(offset = 0L, label = "PredictiveRun seed") {
    ci_jax_key(seed = seed, offset = offset, label = label)
  }
  
  # figure name info 
  FigNameAppend <- sprintf("KW%s_InputAvePool%s_OptimizeImageRep%s_Tag%s",
                           kernelSize, inputAvePoolingSize,
                           optimizeImageRep, figuresTag)
  tagInFigures <- !is.null(figuresTag)
  figuresTag <- ifelse(is.null(figuresTag), yes = "", no = figuresTag)
  
  # make all directory logic explicit
  myGlmnet_coefs <- loss_vec <- NULL
  orig_wd <- getwd()
  if( (cond1 <- substr(figuresPath, start = 0, stop = 1) == ".")  ){
    figuresPath <- gsub(figuresPath, pattern = '\\.', replacement = orig_wd)
  }
  if(!dir.exists(figuresPath)){ dir.create(figuresPath) }
  figuresPath <- paste(strsplit(figuresPath,split="/")[[1]],collapse = "/")
  if(batchSize > length(obsY)){ batchSize <- round(length(obsY) * 0.90) }
  
  XisNull <- is.null( X  )
  if(!XisNull){ if(!"matrix" %in% class(X)){
    message2("Coercing X to matrix class..."); X <- as.matrix(  X )
  } }
  
  if( !XisNull ){ if(is.na(sum(X))){ stop("Error: is.na(sum(X)) is TRUE; check for NAs or that all variables are numeric.") }}
  if( !XisNull ){ if(any(apply(X,2,stats::sd) == 0)){ stop("Error: any(apply(X,2,sd) == 0) is TRUE; a column in X seems to have no variance; drop column!") }}
  prepared_X <- ci_predictive_prepare_x(X = X, n_obs = length(obsY))
  X <- prepared_X$X
  X_mean <- prepared_X$X_mean
  X_sd <- prepared_X$X_sd
  x_ncol <- prepared_X$x_ncol
  training_has_X <- !prepared_X$XisNull

  if(is.null(file)){stop("No file specified for tfrecord!")}
  changed_wd <- F; if(  !is.null(  file  )  ){
    message2("Establishing connection with tfrecord")
    tf_record_name <- file
    if( !grepl(tf_record_name, pattern = "/") ){
      tf_record_name <- paste("./",tf_record_name, sep = "")
    }
    tf_record_name <- strsplit(tf_record_name,split="/")[[1]]
    new_wd <- paste(tf_record_name[-length(tf_record_name)], collapse = "/")
    message2(sprintf("Temporarily re-setting the wd to %s", new_wd ) )
    changed_wd <- T; setwd( new_wd )
    on.exit(try(setwd(orig_wd), silent = TRUE), add = TRUE)
    
    # define video indicator 
    useVideoIndicator <- dataType == "video"
    
    # define tf record 
    tf_dataset <- cienv$tf$data$TFRecordDataset(  tf_record_name[length(tf_record_name)] )
    
    # helper functions
    getParsed_tf_dataset_inference <- function(tf_dataset){
      dataset <- tf_dataset$map( function(x){parse_tfr_element(x, 
                                                               readVideo = useVideoIndicator, 
                                                               image_dtype = image_dtype_tf)} )
      return( dataset <- dataset$batch( as.integer(max(2L,round(batchSize/2L)  ))) )
    }
    
    message2("Setting up iterators...") # - skip the first test_size observations 
    if(!is.null(TFRecordControl)){
      getParsed_tf_dataset_train_Select <- function( tf_dataset ){
        return( tf_dataset$map( function(x){ parse_tfr_element(x, 
                                                               readVideo = useVideoIndicator, 
                                                               image_dtype = image_dtype_tf)},
                                num_parallel_calls = cienv$tf$data$AUTOTUNE) ) 
      }
      getParsed_tf_dataset_train_BatchAndShuffle <- function( tf_dataset ){
        tf_dataset <- tf_dataset$shuffle(buffer_size = cienv$tf$constant(as.integer(TfRecords_BufferScaler*batchSize),
                                                                         dtype=cienv$tf$int64),
                                         reshuffle_each_iteration = T) 
        tf_dataset <- tf_dataset$batch(  as.integer(batchSize)   )
        tf_dataset <- tf_dataset$prefetch( cienv$tf$data$AUTOTUNE ) 
        return( tf_dataset )
      }
      tf_dataset_train <- getParsed_tf_dataset_train_Select(
        tf_dataset$skip(  test_size <-  as.integer( TFRecordControl$nTest)  )
      )$`repeat`(-1L)  
      tf_dataset_train <- getParsed_tf_dataset_train_BatchAndShuffle(tf_dataset_train)
      ds_iterator_train <- reticulate::as_iterator( tf_dataset_train )
    }
    if(is.null(TFRecordControl)){
      getParsed_tf_dataset_train <- function( tf_dataset ){
        dataset <- tf_dataset$map( function(x){ parse_tfr_element(x, readVideo = useVideoIndicator, image_dtype = image_dtype_tf)},
                                   num_parallel_calls = cienv$tf$data$AUTOTUNE)
        dataset <- dataset$shuffle(buffer_size = cienv$tf$constant(as.integer(TfRecords_BufferScaler*batchSize), dtype=cienv$tf$int64),
                                   reshuffle_each_iteration = FALSE) # set FALSE so same train/test split each re-initialization
        dataset <- dataset$batch(  as.integer(batchSize)   )
        dataset <- dataset$prefetch( cienv$tf$data$AUTOTUNE ) 
        return( dataset  )
      }
      
      # shuffle (generating different train/test splits)
      tf_dataset <- cienv$tf$data$Dataset$shuffle(  tf_dataset, 
                                                    buffer_size = cienv$tf$constant(as.integer(10L*TfRecords_BufferScaler*batchSize),
                                                                                    dtype=cienv$tf$int64), reshuffle_each_iteration = F )
      tf_dataset_train <- getParsed_tf_dataset_train( 
        tf_dataset$skip(test_size <-  as.integer(round(testFrac * length(unique(imageKeysOfUnits)) )) ) )$`repeat`(  -1L )
      ds_iterator_train <- reticulate::as_iterator( tf_dataset_train )
    }
    # define inference iterator 
    tf_dataset_inference <- getParsed_tf_dataset_inference( tf_dataset )
    ds_iterator_inference <- reticulate::as_iterator( tf_dataset_inference )
  }
  
  scalePerturbations <- function(im_, key) {
    im_
  }
  if(useTrainingPerturbations){
    trainingPerturbations <- cienv$jax$vmap( 
      trainingPerturbations_OneObs <- function(im_, key){
        # key <- cienv$jax$random$key(c(sample(1:100,1)))
        AB <- ifelse(dataType == "video", yes = 1L, no = 0L)
        which_path <- cienv$jnp$squeeze(cienv$jax$random$categorical(key = key, logits = cienv$jnp$array(t(rep(0, times = 4)))),0L)# generates random # from 0L to 3L
        
        # flip paths
        # which_path of 0L -> do no flips 
        im_ <- cienv$jax$lax$cond(cienv$jnp$equal(which_path,cienv$jnp$array(1L)),
                                  true_fun = function(){ cienv$jnp$flip(im_, 
                                                                        axis = AB+0L) }, 
                                  false_fun = function(){im_})
        im_ <- cienv$jax$lax$cond(cienv$jnp$equal(which_path,cienv$jnp$array(2L)), 
                                  true_fun = function(){ cienv$jnp$flip(im_, 
                                                                        axis = AB+1L) }, 
                                  false_fun = function(){im_})
        im_ <- cienv$jax$lax$cond(cienv$jnp$equal(which_path,cienv$jnp$array(3L)),
                                  true_fun = function(){ cienv$jnp$flip(cienv$jnp$flip(im_, 
                                                                                       axis = AB+0L),
                                                                        axis = AB+1L) }, 
                                  false_fun = function(){im_})
        
        # Add brightness perturbation (scalar addition)
        key <- cienv$jax$random$split(key)  # Use second key from split for next ops; discard first if not needed
        apply_bright <- cienv$jax$random$bernoulli(cienv$jax$random$split(key[[1]])[[1L]], p=0.25)
        im_ <- cienv$jax$lax$cond(apply_bright,
                                  true_fun = function(){ im_ + cienv$jax$random$uniform(cienv$jax$random$split(key[[1]])[[1]], minval=-0.1, maxval=0.1,dtype = im_$dtype)}, # delta noise 
                                  false_fun = function(){ im_ })
        
        # Add contrast perturbation (centered multiplication)
        key <- cienv$jax$random$split(key[[1]])
        apply_contrast <- cienv$jax$random$bernoulli(cienv$jax$random$split(key[[1]])[[1L]], p=0.25)
        im_ <- cienv$jax$lax$cond(apply_contrast,
                                  true_fun = function(){ im_ * cienv$jax$random$uniform(cienv$jax$random$split(key[[1]])[[1L]], minval=0.8, maxval=1.2,dtype=im_$dtype) },
                                  false_fun = function(){ im_ })
        
        # Add Gaussian noise perturbation (per-element)
        key <- cienv$jax$random$split(key[[1L]])
        apply_noise <- cienv$jax$random$bernoulli(cienv$jax$random$split(key[[1]])[[1L]], p=0.25)
        im_ <- cienv$jax$lax$cond(apply_noise,
                                  true_fun = function(){ im_ + cienv$jax$random$normal(cienv$jax$random$split(key[[1]])[[1L]], shape=cienv$jnp$shape(im_),dtype=im_$dtype) * 0.05},
                                  false_fun = function(){ im_ })
        return( im_ ) 
      }, in_axes = list(0L,0L))
  }
  
  InitImageProcessFn <- cienv$jax$jit(function(im, key, inference){
    # expand dims if needed
    if(length(imageKeysOfUnits) == 1){ im <- cienv$jnp$expand_dims(im,0L) }
    
    # normalize
    im <- (im - NORM_MEAN_array) / NORM_SD_array
    
    # downshift resolution if desired
    if(inputAvePoolingSize > 1 & dataType == "image"){
      im <- cienv$jax$vmap(function(imm){
        cienv$jnp$transpose(  cienv$eq$nn$AvgPool2d(kernel_size = as.integer(c(inputAvePoolingSize,inputAvePoolingSize)),
                                                    stride = as.integer(c(inputAvePoolingSize,inputAvePoolingSize)))(
                                                      cienv$jnp$transpose(imm,c(2L,0L,1L)  )), c(1L,2L, 0L)) }, 0L)(im)
    }
    
    # training perturbations
    if(useTrainingPerturbations){
      im <- cienv$jax$lax$cond(inference, true_fun = function(){ im }, 
                               false_fun = function(){  trainingPerturbations(im, 
                                                                             cienv$jax$random$split(key,im$shape[[1]])) } )
    }
    if(useScalePerturbations){
      im <- cienv$jax$lax$cond(inference, true_fun = function(){ im }, 
                               false_fun = function(){  scalePerturbations(im, 
                                                                          cienv$jax$random$split(key,im$shape[[1]])) } )
    }
    return( im  )
  })
  
  message2("Calibrating first moments for input data normalization...")
  NORM_MEAN_array <- GetMoments(ds_iterator_train, 
                                dataType = dataType, 
                                image_dtype = image_dtype, 
                                momentCalIters = 34)
  NORM_SD <- NORM_MEAN_array$NORM_SD; NORM_SD_array <- NORM_MEAN_array$NORM_SD_array
  NORM_MEAN <- NORM_MEAN_array$NORM_MEAN; NORM_MEAN_array <- NORM_MEAN_array$NORM_MEAN_array
  cienv$py_gc$collect()
  
  # Determine if Y is binary or continuous
  is_binary <- length(unique(obsY)) == 2 && all(obsY %in% c(0, 1))
  message2(ifelse(is_binary, "Treating obsY as binary.", "Treating obsY as continuous."))
  
  setwd(orig_wd); ImageRepresentations <- GetImageRepresentations(
    X = X,
    file = file,
    dataType = dataType,
    temporalAggregation = temporalAggregation,
    InitImageProcess = InitImageProcessFn,
    NORM_MEAN = NORM_MEAN,
    NORM_SD = NORM_SD,
    nWidth_ImageRep = nWidth_ImageRep,
    nDepth_ImageRep = nDepth_ImageRep,
    strides = strides,
    nonLinearScaler = nonLinearScaler,
    dropoutRate = dropoutRate,
    droppathRate = droppathRate,
    nDepth_TemporalRep = nDepth_TemporalRep,
    patchEmbedDim = patchEmbedDim,
    batchSize = batchSize,
    imageModelClass = imageModelClass,
    pretrainedModel = pretrainedModel,
    image_dtype = image_dtype,
    image_dtype_tf = image_dtype_tf,
    optimizeImageRep = optimizeImageRep,
    kernelSize = kernelSize,
    inputAvePoolingSize = inputAvePoolingSize,
    TfRecords_BufferScaler = 3L,
    XCrossModal = XCrossModal,
    XForceModal = XForceModal,
    imageKeysOfUnits = (UsedKeys <- unique(imageKeysOfUnits)[seq_len(min(length(unique(imageKeysOfUnits)), max(2L, 2L * batchSize)))]), getRepresentations = T,
    returnContents = T,
    initializingFxns = T,
    bn_momentum = 0.99,
    conda_env = conda_env,
    conda_env_required = conda_env_required,
    Sys.setenv_text = Sys.setenv_text,
    seed = predictive_seed_value(offset = 4003L, label = "PredictiveRun optimized representation seed")  ); setwd(new_wd)
  ImageModel_And_State_And_MPPolicy_List <- ImageRepresentations[["ImageModel_And_State_And_MPPolicy_List"]]
  ImageRepArm_batch_R <- ImageRepresentations[["ImageRepArm_batch_R"]]
  InitImageProcessFn <-  ImageRepresentations[["InitImageProcess"]]
  rm( ImageRepresentations )
  
  batch_axis_name <- "batch"
  DenseList <- DenseStateList <- replicate(nDepth_Dense, list())
  for(d_ in 1L:nDepth_Dense){
    DenseProj_d <- cienv$eq$nn$Linear(in_features = ind_ <- ifelse(d_ == 1, 
                                                                   yes = (nWidth_ImageRep + ifelse(XisNull, no = ncol(X)*(!XCrossModal), yes = 0L)),
                                                                   no =  nWidth_Dense),
                                      out_features = outd_ <- ifelse(d_ == nDepth_Dense,
                                                                     yes = 1L,  no = nWidth_Dense),
                                      use_bias = T, key = predictive_seed_key(offset = d_ + 44L, label = "PredictiveRun dense layer seed"))
    LayerBN_d <- cienv$jnp$array(1)
    DenseStateList[[d_]] <- list('BNState' = cienv$eq$nn$State( LayerBN_d ))
    DenseList[[d_]] <- list("DenseProj" = DenseProj_d,
                            "BN" = LayerBN_d)
  }
  names(DenseList) <- names(DenseStateList) <- paste0("Dense", 1:nDepth_Dense)
  
  GetDense_OneObs <- function(ModelList, ModelList_fixed, m, x, seed, 
                              StateList, MPList, inference){
    if(!XCrossModal){
      if(!XisNull){  m <- cienv$jnp$concatenate(list(m,x))  }
    }
    
    for(d__ in 1:nDepth_Dense){
      eval(parse(text = sprintf("DenseList_d <- ModelList$DenseList$Dense%s",d__)))
      eval(parse(text = sprintf("StateDenseList_d <- StateList$DenseStateList$Dense%s",d__)))
      
      m <- DenseList_d$DenseProj(  m  )
      
      # BN + non-linearity
      if(d__ < nDepth_Dense){
        m <- DenseList_d$BN(m, state = StateDenseList_d, inference = inference)
        eval(parse(text = sprintf("StateList$DenseStateList$Dense%s <- m[[2]]", d__)))
        m <- m[[1]]
        
        # Non-linearity
        m <- cienv$jax$nn$swish(  m   )
      }
    }
    
    return( list(m, StateList)  )
  }
  GetDense_batch <- cienv$jax$vmap(  function(
  ModelList, ModelList_fixed,
  m, x, seed,
  StateList, MPList, inference){
    GetDense_OneObs(ModelList, ModelList_fixed, m, x, seed, 
                    StateList, MPList, inference)
  },
  in_axes = list(NULL, NULL, 0L, 0L, 0L, NULL, NULL, NULL),
  axis_name = batch_axis_name,
  out_axes = list(0L, NULL) )
  GetDense_batch_jit <- cienv$eq$filter_jit(   GetDense_batch  )
  GetPredict_batch <- function( ModelList, ModelList_fixed,
                                m, x, seed,
                                StateList, MPList, inference){
    m <- ImageRepArm_batch_R(ModelList, m, x,
                             StateList, seed, MPList, inference)
    StateList <- m[[2]]; m <- m[[1]]
    
    m <- GetDense_batch(ModelList, ModelList_fixed, m, x, seed, StateList,  MPList, inference)
    StateList <- m[[2]]; m <- m[[1]]
    
    if(is_binary){
      m <- cienv$jax$nn$sigmoid( m )
    } # else linear for continuous
    
    return( list(m, StateList) )
  }
  
  GetLoss <-  function( ModelList, ModelList_fixed,
                        m, x, treat, y, seed, # note: treat unused 
                        StateList, MPList, inference ){
    ModelList <- MPList[[1]]$cast_to_compute( ModelList ) 
    ModelList_fixed <- MPList[[1]]$cast_to_compute( ModelList_fixed ) 
    StateList <- MPList[[1]]$cast_to_compute( StateList ) 
    
    m <- GetPredict_batch( ModelList, ModelList_fixed,
                           m, x, seed,
                           StateList, MPList, inference )
    StateList <- m[[2]]; m <-  m[[1]]
    
    # compute loss
    m <- MPList[[1]]$cast_to_output( m )
    if(is_binary){
      NegLL <-  cienv$jnp$mean( cienv$jnp$negative(  y*cienv$jnp$log(m) + 
                                                       (1-y)*cienv$jnp$log(1-m) )  ) 
    }
    if(!is_binary){
      NegLL <-  cienv$jnp$mean( cienv$jnp$square(m - y) ) 
    }
    
    if(image_dtype_char == "float16"){ 
      NegLL <- MPList[[1]]$cast_to_output( NegLL ) 
      NegLL <- MPList[[2]]$scale( NegLL ) 
      StateList <- MPList[[1]]$cast_to_param( StateList ) 
    }
    
    return( list(NegLL, StateList)  )
  }
  
  gc(); cienv$py_gc$collect()
  GradAndLossAndAux <-  cienv$eq$filter_jit( cienv$eq$filter_value_and_grad( GetLoss, has_aux = T) )
  ModelList <- c(ImageModel_And_State_And_MPPolicy_List[[1]], "DenseList" = list(DenseList))
  StateList <- c(ImageModel_And_State_And_MPPolicy_List[[2]], "DenseStateList" = list(DenseStateList))
  ModelList_fixed <- cienv$jnp$array(0.)
  MPList <- list(cienv$jmp$Policy(compute_dtype=ComputeDtype, 
                                  param_dtype="float32", 
                                  output_dtype=(outputDtype <- ComputeDtype)),
                 cienv$jmp$DynamicLossScale(loss_scale = cienv$jnp$array(2^15,dtype = ComputeDtype ),
                                            min_loss_scale = cienv$jnp$array(2^1.,dtype = ComputeDtype ),
                                            period = 50L))
  ModelList <- MPList[[1]]$cast_to_param( ModelList )
  ModelList_fixed <- MPList[[1]]$cast_to_param( ModelList_fixed )
  rm( ImageModel_And_State_And_MPPolicy_List, DenseStateList, DenseList )
  
  message2("Define trainer...")
  LocalFxnSource(TrainDefine, evaluation_environment = environment())
  
  message2("Starting training...")
  earlyStopThreshold <- NULL
  justCheckIterators <- FALSE
  LocalFxnSource(TrainDo, evaluation_environment = environment())
  
  message2("Getting predicted quantities...")
  predictive_config <- list(
    imageModelClass = imageModelClass,
    pretrainedModel = pretrainedModel,
    optimizeImageRep = optimizeImageRep,
    nWidth_ImageRep = nWidth_ImageRep,
    nDepth_ImageRep = nDepth_ImageRep,
    nWidth_Dense = nWidth_Dense,
    nDepth_Dense = nDepth_Dense,
    XCrossModal = XCrossModal,
    XForceModal = XForceModal,
    strides = strides,
    nonLinearScaler = nonLinearScaler,
    nDepth_TemporalRep = nDepth_TemporalRep,
    patchEmbedDim = patchEmbedDim,
    dropoutRate = dropoutRate,
    droppathRate = droppathRate,
    batchSize = batchSize,
    dataType = dataType,
    temporalAggregation = temporalAggregation,
    inputAvePoolingSize = inputAvePoolingSize,
    useTrainingPerturbations = useTrainingPerturbations,
    useScalePerturbations = useScalePerturbations,
    kernelSize = kernelSize,
    image_dtype = image_dtype_char,
    is_binary = is_binary,
    seed_template = seed
  )

  score_out <- ci_predictive_score_existing_model(
    config = predictive_config,
    ModelList = ModelList,
    StateList = StateList,
    ModelList_fixed = ModelList_fixed,
    MPList = MPList,
    ImageRepArm_batch_R = ImageRepArm_batch_R,
    InitImageProcessFn = InitImageProcessFn,
    X = X,
    XisNull = !training_has_X,
    imageKeysOfUnits = imageKeysOfUnits,
    file = file
  )
  predictedY <- score_out$predictedY

  trainIndices <- which(imageKeysOfUnits %in% keysUsedInTraining)
  testIndices <- which(!imageKeysOfUnits %in% keysUsedInTraining)

  safe_auc <- function(y_true, y_pred) {
    if (length(unique(y_true)) < 2L) {
      return(NA_real_)
    }
    as.numeric(pROC::roc(y_true, y_pred)$auc)
  }
  safe_auprc <- function(y_true, y_pred) {
    if (length(unique(y_true)) < 2L) {
      return(NA_real_)
    }
    PRROC::pr.curve(
      scores.class0 = y_pred[y_true == 1],
      scores.class1 = y_pred[y_true == 0],
      curve = FALSE
    )$auc.integral
  }

  ModelEvaluationMetrics <- list()
  if(is_binary){
    pred_baseline_out <- rep(mean(obsY[trainIndices]), length(testIndices))
    pred_baseline_in <- rep(mean(obsY[trainIndices]), length(trainIndices))
    lossCE_OUT <- -mean(obsY[testIndices] * log(predictedY[testIndices]) + (1 - obsY[testIndices]) * log(1 - predictedY[testIndices]))
    lossCE_IN <- -mean(obsY[trainIndices] * log(predictedY[trainIndices]) + (1 - obsY[trainIndices]) * log(1 - predictedY[trainIndices]))

    ModelEvaluationMetrics <- list(
      "CELoss_out" = lossCE_OUT,
      "CELoss_in" = lossCE_IN,
      "CELoss_out_baseline" = -mean(obsY[testIndices] * log(pred_baseline_out) + (1 - obsY[testIndices]) * log(1 - pred_baseline_out)),
      "CELoss_in_baseline" = -mean(obsY[trainIndices] * log(pred_baseline_in) + (1 - obsY[trainIndices]) * log(1 - pred_baseline_in)),
      "Accuracy_out" = mean((predictedY[testIndices] > 0.5) == obsY[testIndices]),
      "Accuracy_in" = mean((predictedY[trainIndices] > 0.5) == obsY[trainIndices]),
      "AUC_out" = safe_auc(obsY[testIndices], predictedY[testIndices]),
      "AUC_in" = safe_auc(obsY[trainIndices], predictedY[trainIndices]),
      "AUPRC_out" = safe_auprc(obsY[testIndices], predictedY[testIndices]),
      "AUPRC_in" = safe_auprc(obsY[trainIndices], predictedY[trainIndices])
    )
  } else {
    mse_OUT <- mean((obsY[testIndices] - predictedY[testIndices])^2)
    mse_IN <- mean((obsY[trainIndices] - predictedY[trainIndices])^2)
    r2_OUT <- 1 - mse_OUT / stats::var(obsY[testIndices])
    r2_IN <- 1 - mse_IN / stats::var(obsY[trainIndices])

    ModelEvaluationMetrics <- list(
      "MSE_out" = mse_OUT,
      "MSE_in" = mse_IN,
      "R2_out" = r2_OUT,
      "R2_in" = r2_IN
    )
  }

  if (!is.null(metricsPath)) {
    ci_predictive_ensure_parent_dir(metricsPath)
    saveRDS(ModelEvaluationMetrics, file = metricsPath)
  }

  manifest <- ci_predictive_make_manifest(
    config = predictive_config,
    NORM_MEAN = NORM_MEAN,
    NORM_SD = NORM_SD,
    X_mean = X_mean,
    X_sd = X_sd,
    x_ncol = x_ncol,
    training_has_X = training_has_X
  )
  if (!is.null(modelPath)) {
    ci_predictive_ensure_parent_dir(modelPath)
    cienv$eq$tree_serialise_leaves(path.expand(modelPath), list(ModelList, StateList))
    saveRDS(manifest, file = ci_predictive_meta_path(modelPath))
  }

  if (xor(is.null(fileTransport), is.null(imageKeysOfUnitsTransport))) {
    stop("fileTransport and imageKeysOfUnitsTransport must either both be NULL or both be supplied.", call. = FALSE)
  }
  if (is.null(fileTransport) && !is.null(XTransport)) {
    stop("XTransport was supplied without fileTransport.", call. = FALSE)
  }

  predictedY_transport <- NULL
  if(!is.null(fileTransport) && !is.null(imageKeysOfUnitsTransport)){
    ci_predictive_validate_transport_x(
      training_has_X = training_has_X,
      XTransport = XTransport,
      context = "PredictiveRun transport scoring"
    )
    prepared_X_transport <- ci_predictive_prepare_x(
      X = XTransport,
      n_obs = length(imageKeysOfUnitsTransport),
      x_stats = list(X_mean = X_mean, X_sd = X_sd),
      x_ncol = x_ncol
    )
    predictedY_transport <- ci_predictive_score_existing_model(
      config = manifest,
      ModelList = ModelList,
      StateList = StateList,
      ModelList_fixed = ModelList_fixed,
      MPList = MPList,
      ImageRepArm_batch_R = ImageRepArm_batch_R,
      InitImageProcessFn = InitImageProcessFn,
      X = prepared_X_transport$X,
      XisNull = !training_has_X,
      imageKeysOfUnits = imageKeysOfUnitsTransport,
      file = fileTransport
    )$predictedY
  }
  
  if( changed_wd ){ setwd(  orig_wd  ) }
  
  return( list(
    "predictedY" = predictedY,
    "ModelEvaluationMetrics" = ModelEvaluationMetrics,
    "predictedY_transport" = predictedY_transport,
    "trainIndices" = trainIndices,
    "testIndices" = testIndices
  ) )
}
